woid/apps/services/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url


urlpatterns = patterns('woid.apps.services.views',
    url(r'^$', 'index', name='index'),
    url(r'^archive/$', 'archive', name='archive'),
    url(r'^(?P<year>[0-9]{4})/$', 'year', name='year'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', 'month', name='month'),
    url(r'^(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$', 'day', name='day'),
)

woid/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = patterns('',
    url(r'^$', 'woid.apps.services.views.front_page', name='front_page'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/' }, name='logout'),
    url(r'^signup/', CreateView.as_view(template_name='registration/signup.html', form_class=UserCreationForm, success_url='/'), name='signup'),
    url(r'^about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    url(r'^status/', 'woid.apps.core.views.status', name='status'),
    url(r'^cookies/', TemplateView.as_view(template_name='core/cookies.html'), name='cookies'),
    url(r'^privacy/', TemplateView.as_view(template_name='core/privacy.html'), name='privacy'),
    url(r'^terms/', TemplateView.as_view(template_name='core/terms.html'), name='terms'),
    url(r'^(?P<slug>[-_\w]+)/', include('woid.apps.services.urls', namespace='services')),
    url(r'^admin/', include(admin.site.urls)),
)

woid/apps/accounts/models.py
from django.db import models

# Create your models here.

woid/apps/core/models.py
from django.db import models

# Create your models here.

woid/apps/services/models.py
# coding: utf-8

from django.db import models

from woid.apps.services.managers import ServiceManager, StoryManager


class Service(models.Model):
    GOOD = 'G'
    ERROR = 'E'
    CRAWLING = 'C'
    CURRENT_STATUS = (
        (GOOD, u'✓ good'),
        (ERROR, u'× error'),
        (CRAWLING, u'~ running')
        )

    name = models.CharField(max_length=255)
    slug = models.SlugField()
    url = models.URLField()
    story_url = models.URLField()
    last_run = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=1, default=GOOD, choices=CURRENT_STATUS)

    objects = ServiceManager()

    class Meta:
        verbose_name = 'service'
        verbose_name_plural = 'services'
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def to_dict(self):
        return {
            'name': self.name,
            'slug': self.slug,
            'url': self.url
        }


class Story(models.Model):
    TEXT = 'T'
    URL = 'U'
    IMAGE = 'I'
    CONTENT_TYPES = (
        (TEXT, 'text'),
        (URL, 'url'),
        (IMAGE, 'image'),
    )

    NEW = 'N'
    OK = 'O'
    ERROR = 'E'
    STATUS = (
        (NEW, 'New'),
        (OK, 'Ok'),
        (ERROR, 'Error'),
    )

    service = models.ForeignKey(Service, related_name='stories')
    code = models.CharField(max_length=255)
    title = models.CharField(max_length=500, null=True, blank=True)
    url = models.URLField(max_length=2000, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    content_type = models.CharField(max_length=1, choices=CONTENT_TYPES, null=True, blank=True)
    start_comments = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    start_score = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    date = models.DateField(auto_now_add=True, db_index=True)
    status = models.CharField(max_length=1, default=NEW, choices=STATUS)
    top_ten = models.BooleanField(default=False)
    nsfw = models.BooleanField(default=False)
    description = models.CharField(max_length=2000, null=True, blank=True)

    objects = StoryManager()

    class Meta:
        verbose_name = 'story'
        verbose_name_plural = 'stories'
        unique_together = (('service', 'code', 'date'),)
        ordering = ('-score',)

    def __unicode__(self):
        return self.code

    def build_url(self):
        self.url = u'{0}{1}'.format(self.service.story_url, self.code)
        return self.url

    def get_template(self):
        template = u'services/includes/{0}_story.html'.format(self.service.slug)
        return template

    def to_dict(self):
        return {
            'code': self.code,
            'title': self.title,
            'url': self.url,
            'comments': self.comments,
            'score': self.score,
            'description': self.description
        }


class StoryUpdate(models.Model):
    story = models.ForeignKey(Story, related_name='updates')
    comments_changes = models.IntegerField(default=0)
    score_changes = models.IntegerField(default=0)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'services_story_update'
        verbose_name = 'story update'
        verbose_name_plural = 'stories updates'

    def __unicode__(self):
        return self.story.code

woid/apps/accounts/views.py
from django.shortcuts import render

# Create your views here.

woid/apps/core/views.py
# coding: utf-8

from django.shortcuts import render

from woid.apps.services.models import Service


def status(request):
    services = Service.objects.all()
    return render(request, 'core/status.html', { 'services': services })

woid/apps/services/views.py
# coding: utf-8

import json
from collections import OrderedDict
from itertools import groupby
import datetime

from django.http import HttpResponse
from django.db.models import Max
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.shortcuts import render, get_object_or_404

from woid.apps.services.models import Service, Story
from woid.apps.services.utils import remove_duplicates


def stories(request, service, queryset, subtitle):
    paginator = Paginator(queryset, 100)
    page = request.GET.get('page')
    try:
        stories = paginator.page(page)
    except PageNotAnInteger:
        stories = paginator.page(1)
    except EmptyPage:
        stories = paginator.page(paginator.num_pages)

    if stories.number > 1:
        start = (stories.number - 1) * 100 + 1
    else:
        start = 1

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        stories_dict = map(lambda story: story.to_dict(), stories)
        dump = json.dumps({
            'service': service.to_dict(),
            'stories': stories_dict,
            'subtitle': subtitle
        })
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/stories.html', {
            'service': service,
            'stories': stories,
            'subtitle': subtitle,
            'start': start
        })

def front_page(request):
    today = timezone.now()
    stories = list()
    services = Service.objects.all()
    for service in services:
        top_story = service.stories.filter(status=Story.OK, date=today).order_by('-score').first()
        if top_story:
            stories.append(top_story)
    subtitle = today.strftime('%d %b %Y')

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        stories_dict = map(lambda story: story.to_dict(), stories)
        dump = json.dumps({
            'stories': stories_dict,
            'subtitle': subtitle
        })
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/front_page.html', { 'stories': stories, 'subtitle': subtitle })

def index(request, slug):
    today = timezone.now()
    return day(request, slug, today.year, today.month, today.day)

def year(request, slug, year):
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories.filter(status=Story.OK, date__year=year)
    return stories(request, service, queryset, year)

def month(request, slug, year, month):
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories.filter(status=Story.OK, date__year=year, date__month=month)
    subtitle = timezone.datetime(int(year), int(month), 1).strftime('%b %Y')
    return stories(request, service, queryset, subtitle)

def day(request, slug, year, month, day):
    date = datetime.datetime(int(year), int(month), int(day))
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories.filter(status=Story.OK, date=date)[:10]
    subtitle = timezone.datetime(int(year), int(month), int(day)).strftime('%d %b %Y')
    return stories(request, service, queryset, subtitle)

def archive(request, slug):
    service = get_object_or_404(Service, slug=slug)

    dates = service.stories.all().order_by('-date').values_list('date', flat=True)
    str_dates = map(lambda date: date.strftime('%Y-%m-%d'), dates)
    str_dates = remove_duplicates(str_dates)

    archive = OrderedDict()
    for year, months in groupby(str_dates, lambda date: date[:4]):
        archive[year] = OrderedDict()
        for month, days in groupby(months, lambda date: date[5:7]):
            archive[year][month] = list()
            for day in days:
                archive[year][month].append(day[8:10])

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        dump = json.dumps(archive)
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/archive.html', {
            'service': service,
            'archive': archive
        })

woid/templates/services/archive.html
{% extends 'base.html' %}

{% block title %}{{ service.name|title }}'s Archive · Woid{% endblock %}

{% load staticfiles calendar_helpers %}

{% block javascript %}
  <script src="{% static 'js/services/stories.js' %}"></script>
{% endblock %}

{% block content %}
  <h2>{{ service.name }} <small>(archive)</small></h2>
  {% include 'services/includes/menu.html' %}
  
  {% for year, months in archive.iteritems %}
    <div class="calendar cf">
      <h3><a href="{% url 'services:year' service.slug year %}">{{ year }}</a></h3>
      <div class="months cf">
        {% for month, days in months.iteritems %}
          <div class="month">
            {% month_calendar year month days service %}
          </div>
        {% endfor %}
      </div>
    </div>
  {% endfor %}

{% endblock %}

woid/templates/services/front_page.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'js/services/stories.js' %}"></script>
{% endblock %}

{% block content %}
  <h2>front page <small>({{ subtitle }})</small></h2>
  <ul class="stories">
    {% for story in stories %}
      {% include story.get_template with append_service=True %}
    {% endfor %}
  </ul>
{% endblock %}

woid/templates/services/index.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

woid/templates/services/stories.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ service.name }} · Woid{% endblock %}

{% block javascript %}
  <script src="{% static 'js/services/stories.js' %}"></script>
{% endblock %}

{% block content %}
  <h2>{{ service.name }} <small>({{ subtitle }})</small></h2>
  {% include 'services/includes/menu.html' %}
  <ol class="stories" start="{{ start }}">
    {% for story in stories %}
      {% include story.get_template %}
    {% endfor %}
  </ol>

  {% if stories.paginator.num_pages > 1 %}
    <ul class="paginator">
      {% if stories.has_previous %}
        <li><a href="?page={{ stories.previous_page_number }}">&laquo; previous</a></li>
      {% else %}
        <li>&laquo; previous</li>
      {% endif %}

      {% for i in stories.paginator.page_range %}
        {% if stories.number == i %}
          <li>{{ i }}</li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if stories.has_next %}
        <li><a href="?page={{ stories.next_page_number }}">next &raquo;</a></li>
      {% else %}
        <li>next &raquo;</li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}